version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u sjega93 -p Ruby240895!
  build:
    commands:
      - docker build -t sjega93/test:latest .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker images
      - docker push sjega93/test:latest